### PR TITLE
Changed circle pads into Vias, Added Star Pattern & Changed Default Via size/drill

### PR DESCRIPTION
**Pull request by Phara0h**
* Changed circle pads into actual Vias
* Added Star Pattern for basic RF stitching
* Changed Default Via sizes and drill to a more standard fab size.

### CODE REVIEW

**Comment by jsreynaud** [comment]
Thanks for your submission. I had fix some little mistake:
- netname in via creation
- adding a flag (dirty way: set timestamp as 33) to allow via deletions (and only thoses via)
- Fix interface in fbp file instead of generated .py
- Cleanup not more necessary method (preparefootprint)

**Comment by Phara0h** [comment]
Sorry about that, thanks for helping clean it up. I don't know python, I was just winging it. I know over 10+ other langs which helped for the work though. Do you run the stable version of kicad (v4.0.x)? If so does it work on that version? I use the nightly build (v5.x)  

P.S Thanks for creating this plugin, it saves me so much time at work when I'm doing hardware designs!

**Comment by jsreynaud** [comment]
I run nightly build. It will not work on V4 since there is no action menu feature. But V5 is close to be released (RC1 is out since a couple a weeks...)

**Comment by Phara0h** [comment]
Perfect, run v5 is so worth the possible unstableness/bugs been doing it since the start pretty much :) Happy pixie rangling

**Pull request merged**
